from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('admin-page', views.admin_2, name='admin-page'),
    path('admin-login', views.admin_login, name='admin-login'),
    path('add-student', views.add_student, name='add-student'),
    path('add-courses', views.add_course, name='add-courses'),
    path('view-courses', views.view_course, name='view-courses'),
    path('view-student', views.view_student, name='view-student'),
    path('add-user', views.add_user, name='add-user'),
    path('view-user', views.view_user, name='view-user'),
    path('update-student/<int:id>', views.update_student, name='update-student'),
    path('update-staff/<int:id>', views.update_staff, name='update-staff'),
    path('student-logout', views.student_logout, name='student-logout'),
    path('admin-logout', views.admin_logout, name='admin-logout'),
    path('level', views.level, name='level'),
    path('take-attendance-for-level1', views.take_attendance_for_level1, name='take-attendance-for-level1'),
    path('take-attendance-for-level2', views.take_attendance_for_level2, name='take-attendance-for-level2'),
    path('student-logout', views.student_logout, name='student-logout'),
    path('lecturer-logout', views.lecturer_logout, name='lecturer-logout'),
    path('lecturer-login', views.lecturer_login, name='lecturer-login'),
    path('lecturer-page', views.lecturer_page, name='lecturer-page'),
    path('take-student-attendance', views.take_student_attendance, name='take-student-attendance'),
    path('view-student-attendance', views.view_student_attendance, name='view-student-attendance'),
    path('student-page', views.student_page, name='student-page'),
    path('update/<int:id>', views.update, name='update'),
    path('update/updaterecord/<int:id>', views.updaterecord, name='updaterecord'),
    path('student-course-view', views.student_course_view, name='student-course-view'),
    path('request-for-delete-lec/<int:id>', views.lec_request_for_delete, name='request-for-delete-lec'),
    path('request-for-delete-stu/<int:id>', views.stu_request_for_delete, name='request-for-delete-stu'),
    path('lec-delete/<int:id>', views.lec_delete, name='lec-delete'),
    path('stu-delete/<int:id>', views.stu_delete, name='stu-delete'),
    path('request-for-delete/<int:id>', views.request_for_delete, name='request-for-delete'),
    path('course-request-for-delete/<int:id>', views.course_request_for_delete, name='course-request-for-delete'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('student-login', views.student_login, name='student-login'),
    path('student-course-registration', views.student_course_registration, name='student-course-registration'),
    path('student-attendance-view', views.student_attendance_view, name='student-attendance-view'),
]