# Generated by Django 4.1.7 on 2023-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
