# Generated by Django 4.1.7 on 2023-04-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aams', '0002_lecturer_id_user_student_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
