# Generated by Django 4.2 on 2023-05-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aams', '0003_studentcourse_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profileImg',
            field=models.ImageField(default='user.png', upload_to='students-pics'),
        ),
    ]
